# Generated by Django 6.1.1 on 2026-09-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excert',
            new_name='excerpt',
        ),
    ]
